# Generated by Django 4.2.6 on 2023-11-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=200)),
                ('authorname', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=200)),
                ('publishdate', models.DateField()),
            ],
        ),
    ]
