# Generated by Django 4.2.6 on 2023-11-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_books_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='image',
            new_name='profile_pic',
        ),
    ]
