# Generated by Django 4.2.6 on 2023-11-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_books_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publishdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
